### ISSUE TITLE
Excerpts on Landing Page too long

### ISSUE THREAD

**Issue by o-s-warren** [FitzwilliamMuseum/collections-up-close#18]
The text for each blog under the title looks wordy with a lot of small text under the picture.  Less text in a bigger font would look better on the page, so cut this down to 1 sentence. (From now on, we’ll ask people to write a teaser sentence under the title when they submit new posts, to tickle interest and get people to click into the full post.  This would make a big difference to this new style of presenting the content.  It needs to be short to encourage further reading while allowing for larger text to get away from all the words mentioned above.)

**Comment by portableant** [comment]
You could use an inbuilt function to shorten the text presented. Eg https://developer.wordpress.org/reference/functions/wp_trim_excerpt/

**Comment by o-s-warren** [comment]
Useful! Thanks Dan
